name: Tests
on:
  pull_request:
    paths:
      - .github/workflows/tests.yml
      - hemm/**
      - pyproject.toml

jobs:
  code-format:
    name: check code format using black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
  lint:
    name: Check linting using ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1